"use strict";
const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const ROOT=__dirname,DB_FILE=process.env.DB_FILE?path.resolve(process.env.DB_FILE):path.join(ROOT,"data","db.json"),DATA_DIR=path.dirname(DB_FILE),PORT=Number(process.env.PORT)||80,STALE_SHOT_MS=Math.max(5000,Number(process.env.STALE_SHOT_MS)||35000);
const STATUS=Object.freeze({OFFLINE:0,ONLINE:1,IN_ROOM:2,IN_GAME:4}),GAME_MODES=["EIGHT","SNOOKER","CHESS","FIVE","GO"];
const CHESS_INITIAL=[
  ["C0","M0","X0","S0","J0","S1","X1","M1","C1"],
  [null,null,null,null,null,null,null,null,null],
  [null,"P0",null,null,null,null,null,"P1",null],
  ["Z0",null,"Z1",null,"Z2",null,"Z3",null,"Z4"],
  [null,null,null,null,null,null,null,null,null],
  [null,null,null,null,null,null,null,null,null],
  ["z0",null,"z1",null,"z2",null,"z3",null,"z4"],
  [null,"p0",null,null,null,null,null,"p1",null],
  [null,null,null,null,null,null,null,null,null],
  ["c0","m0","x0","s0","j0","s1","x1","m1","c1"]
];
const cloneBoard=board=>board.map(row=>row.slice()),chessSide=piece=>piece&&piece[0]===piece[0].toLowerCase()?0:1,chessType=piece=>piece?.[0].toLowerCase(),insideChess=(x,y)=>Number.isInteger(x)&&Number.isInteger(y)&&x>=0&&x<9&&y>=0&&y<10;
function clearLine(board,fx,fy,tx,ty){let count=0;if(fx===tx)for(let y=Math.min(fy,ty)+1;y<Math.max(fy,ty);y++)if(board[y][fx])count++;else{}else if(fy===ty)for(let x=Math.min(fx,tx)+1;x<Math.max(fx,tx);x++)if(board[fy][x])count++;else{}else return-1;return count}
/* 中国象棋基础着法。这里只判断棋子的运动规则；“不能送将”由 chessMoveLegal 的模拟盘面二次判断。 */
function chessPseudoLegal(board,fx,fy,tx,ty){if(!insideChess(fx,fy)||!insideChess(tx,ty)||(fx===tx&&fy===ty))return false;const piece=board[fy][fx],target=board[ty][tx];if(!piece||target&&chessSide(target)===chessSide(piece))return false;const side=chessSide(piece),type=chessType(piece),dx=tx-fx,dy=ty-fy,ax=Math.abs(dx),ay=Math.abs(dy);
  if(type==="c")return(fx===tx||fy===ty)&&clearLine(board,fx,fy,tx,ty)===0;
  if(type==="m"){if(!((ax===1&&ay===2)||(ax===2&&ay===1)))return false;const legX=fx+(ax===2?Math.sign(dx):0),legY=fy+(ay===2?Math.sign(dy):0);return!board[legY][legX]}
  if(type==="x")return ax===2&&ay===2&&!board[fy+dy/2][fx+dx/2]&&(side===0?ty>=5:ty<=4);
  if(type==="s")return ax===1&&ay===1&&tx>=3&&tx<=5&&(side===0?ty>=7:ty<=2);
  if(type==="j"){if(target&&chessType(target)==="j"&&fx===tx&&clearLine(board,fx,fy,tx,ty)===0)return true;return ax+ay===1&&tx>=3&&tx<=5&&(side===0?ty>=7:ty<=2)}
  if(type==="p"){if(!(fx===tx||fy===ty))return false;const blockers=clearLine(board,fx,fy,tx,ty);return target?blockers===1:blockers===0}
  if(type==="z"){const forward=side===0?-1:1,crossed=side===0?fy<=4:fy>=5;return dx===0&&dy===forward||crossed&&dy===0&&ax===1}
  return false
}
function chessInCheck(board,side){let king=null;for(let y=0;y<10;y++)for(let x=0;x<9;x++){const p=board[y][x];if(p&&chessSide(p)===side&&chessType(p)==="j")king={x,y}}if(!king)return true;for(let y=0;y<10;y++)for(let x=0;x<9;x++){const p=board[y][x];if(p&&chessSide(p)!==side&&chessPseudoLegal(board,x,y,king.x,king.y))return true}return false}
function chessMoveLegal(board,side,from,to){const{ x:fx,y:fy}=from,{x:tx,y:ty}=to;if(!insideChess(fx,fy)||!insideChess(tx,ty)||chessSide(board[fy][fx])!==side||!chessPseudoLegal(board,fx,fy,tx,ty))return false;const next=cloneBoard(board);next[ty][tx]=next[fy][fx];next[fy][fx]=null;return!chessInCheck(next,side)}
function chessHasMove(board,side){for(let fy=0;fy<10;fy++)for(let fx=0;fx<9;fx++)if(board[fy][fx]&&chessSide(board[fy][fx])===side)for(let ty=0;ty<10;ty++)for(let tx=0;tx<9;tx++)if(chessMoveLegal(board,side,{x:fx,y:fy},{x:tx,y:ty}))return true;return false}
const emptyBoard=size=>Array.from({length:size},()=>Array(size).fill(0));
const boardHash=board=>board.map(row=>row.join("")).join("/");
const gridNeighbors=(x,y,size)=>[[x-1,y],[x+1,y],[x,y-1],[x,y+1]].filter(([nx,ny])=>nx>=0&&ny>=0&&nx<size&&ny<size);
function goGroup(board,x,y){const color=board[y][x],size=board.length,stones=[],liberties=new Set(),seen=new Set([`${x},${y}`]),stack=[[x,y]];while(stack.length){const[sx,sy]=stack.pop();stones.push([sx,sy]);for(const[nx,ny]of gridNeighbors(sx,sy,size)){if(board[ny][nx]===0)liberties.add(`${nx},${ny}`);else if(board[ny][nx]===color&&!seen.has(`${nx},${ny}`)){seen.add(`${nx},${ny}`);stack.push([nx,ny])}}}return{stones,liberties}}
function goScore(board,komi){const size=board.length,score=[0,komi],seen=new Set();for(let y=0;y<size;y++)for(let x=0;x<size;x++){const color=board[y][x];if(color){score[color-1]++;continue}const key=`${x},${y}`;if(seen.has(key))continue;const region=[],border=new Set(),stack=[[x,y]];seen.add(key);while(stack.length){const[pX,pY]=stack.pop();region.push([pX,pY]);for(const[nx,ny]of gridNeighbors(pX,pY,size)){const value=board[ny][nx],nextKey=`${nx},${ny}`;if(value)border.add(value);else if(!seen.has(nextKey)){seen.add(nextKey);stack.push([nx,ny])}}}if(border.size===1)score[[...border][0]-1]+=region.length}return{black:score[0],white:score[1]}}
function newGame(mode){const base={currentTurn:0,rolling:false,activeShooter:null,shotToken:null,shotStartedAt:null,snapshot:null,lastAction:null,round:1,resultRecorded:false,restartRequest:null,finished:false,winner:null};if(mode==="CHESS")return{...base,chess:{board:cloneBoard(CHESS_INITIAL),currentTurn:0,winner:null,status:"PLAYING",moveNumber:0,lastMove:null,check:false}};if(mode==="FIVE")return{...base,five:{size:15,board:emptyBoard(15),currentTurn:0,winner:null,status:"PLAYING",moveNumber:0,lastMove:null}};if(mode==="GO"){const board=emptyBoard(19);return{...base,go:{size:19,komi:6.5,board,currentTurn:0,winner:null,status:"PLAYING",moveNumber:0,lastMove:null,captures:[0,0],passCount:0,history:[boardHash(board)],result:null}}}return base}
if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true});
if(!fs.existsSync(DB_FILE))fs.writeFileSync(DB_FILE,JSON.stringify({users:[],friendRequests:[],rooms:[]},null,2));
let db=JSON.parse(fs.readFileSync(DB_FILE,"utf8"));db.users||=[];db.friendRequests||=[];db.rooms||=[];
function ensureStats(user){user.stats||={};for(const mode of GAME_MODES)user.stats[mode]||={wins:0,losses:0,draws:0};return user.stats}
for(const user of db.users)ensureStats(user);for(const room of db.rooms){room.game||=newGame(room.mode);room.game.round||=1;room.game.restartRequest||=null;if(room.game.rolling&&!room.game.shotStartedAt)room.game.shotStartedAt=Date.now();if(room.game.resultRecorded===undefined)room.game.resultRecorded=room.status!=="STARTED"}
const sessions=new Map(),streams=new Map();
const id=prefix=>`${prefix}_${crypto.randomBytes(8).toString("hex")}`;
const now=()=>new Date().toISOString();
function settledResult(room){if(room.game.finished)return{done:true,winner:room.game.winner};const state=room.mode==="CHESS"?room.game.chess:room.mode==="FIVE"?room.game.five:room.mode==="GO"?room.game.go:null;if(state?.status==="FINISHED")return{done:true,winner:state.winner};if(["EIGHT","SNOOKER"].includes(room.mode)&&room.game.snapshot?.gameState==="GAME_OVER")return{done:true,winner:room.game.snapshot.winner};return{done:false,winner:null}}
function recordRoomResult(room){if(room.game.resultRecorded||!room.guestId)return;const result=settledResult(room);if(!result.done)return;const players=[db.users.find(u=>u.id===room.hostId),db.users.find(u=>u.id===room.guestId)];if(players.some(player=>!player))return;for(const player of players)ensureStats(player);if(result.winner===0||result.winner===1){players[result.winner].stats[room.mode].wins++;players[1-result.winner].stats[room.mode].losses++}else{players[0].stats[room.mode].draws++;players[1].stats[room.mode].draws++}room.game.resultRecorded=true;room.game.finished=true;room.game.winner=result.winner}
function save(){for(const room of db.rooms)recordRoomResult(room);const tmp=DB_FILE+".tmp";fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,DB_FILE)}
function cookies(req){return Object.fromEntries((req.headers.cookie||"").split(";").map(v=>v.trim().split("=")).filter(v=>v.length===2).map(([k,v])=>[k,decodeURIComponent(v)]))}
function currentUser(req){const userId=sessions.get(cookies(req).sid);return db.users.find(user=>user.id===userId)||null}
function activeRoom(userId){return db.rooms.find(room=>room.status!=="FINISHED"&&(room.hostId===userId||room.guestId===userId))||null}
function statusOf(userId){let value=streams.get(userId)?.size?STATUS.ONLINE:STATUS.OFFLINE,room=activeRoom(userId);if(room)value|=room.status==="STARTED"?STATUS.IN_GAME:STATUS.IN_ROOM;return value}
function publicUser(user){return{id:user.id,username:user.username,status:statusOf(user.id),createdAt:user.createdAt}}
function publicRoom(room){return{id:room.id,host:publicUser(db.users.find(u=>u.id===room.hostId)),guest:room.guestId?publicUser(db.users.find(u=>u.id===room.guestId)):null,mode:room.mode,status:room.status,modeLocked:room.modeLocked,revision:room.revision,createdAt:room.createdAt,game:{currentTurn:room.game.currentTurn,rolling:room.game.rolling,snapshot:room.game.snapshot,lastAction:room.game.lastAction||null,activeShooter:room.game.activeShooter||null,shotToken:room.game.shotToken||null,shotStartedAt:room.game.shotStartedAt||null,round:room.game.round||1,finished:!!room.game.finished,winner:room.game.winner??null,restartRequest:room.game.restartRequest||null,chess:room.mode==="CHESS"?room.game.chess:null,five:room.mode==="FIVE"?room.game.five:null,go:room.mode==="GO"?room.game.go:null}}}
function json(res,status,data,headers={}){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...headers});res.end(JSON.stringify(data))}
function fail(res,status,message){json(res,status,{error:message})}
async function body(req){let raw="";for await(const chunk of req){raw+=chunk;if(raw.length>1e6)throw Error("请求过大")}if(!raw)return{};try{return JSON.parse(raw)}catch{throw Error("JSON 格式错误")}}
function hashPassword(password,salt=crypto.randomBytes(16).toString("hex")){return{salt,hash:crypto.scryptSync(password,salt,64).toString("hex")}}
function verifyPassword(password,user){const candidate=hashPassword(password,user.salt).hash;return crypto.timingSafeEqual(Buffer.from(candidate,"hex"),Buffer.from(user.passwordHash,"hex"))}
function sendEvent(userId,event){for(const res of streams.get(userId)||[]){res.write(`data: ${JSON.stringify(event)}\n\n`)}}
function broadcastRefresh(){for(const userId of streams.keys())sendEvent(userId,{type:"REFRESH",at:Date.now()})}
function roomEvent(room,event){for(const userId of [room.hostId,room.guestId].filter(Boolean))sendEvent(userId,event)}
function setSession(res,userId){const sid=crypto.randomBytes(24).toString("hex");sessions.set(sid,userId);return{"Set-Cookie":`sid=${sid}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800`}}
function requireAuth(req,res){const user=currentUser(req);if(!user)fail(res,401,"请先登录");return user}
function requireRoom(req,res,roomId,user){const room=db.rooms.find(r=>r.id===roomId);if(!room){fail(res,404,"房间不存在");return null}if(room.hostId!==user.id&&room.guestId!==user.id){fail(res,403,"你不在该房间");return null}return room}
function modeName(mode){return mode==="SNOOKER"?"斯诺克":mode==="EIGHT"?"中式八球":mode==="CHESS"?"中国象棋":mode==="FIVE"?"五子棋":mode==="GO"?"围棋":null}
/* 台球快照必须包含一套且仅一套固定球号。服务端不接受重复 ID、缺球或非有限坐标，防止坏快照让球的身份/颜色错位。 */
function validBilliardsSnapshot(snapshot,mode){if(!snapshot||snapshot.mode!==mode||![0,1].includes(snapshot.currentTurn)||!Array.isArray(snapshot.balls))return false;const expected=mode==="EIGHT"?Array.from({length:16},(_,i)=>i):[0,...Array.from({length:15},(_,i)=>101+i),202,203,204,205,206,207];if(snapshot.balls.length!==expected.length)return false;const allowedStates=new Set(["ACTIVE","SINKING","POCKETED"]),seen=new Set();for(const ball of snapshot.balls){const id=Number(ball?.id);if(!expected.includes(id)||seen.has(id)||!allowedStates.has(ball.state))return false;seen.add(id);if(![ball.x,ball.y,ball.vx,ball.vy,ball.sink,ball.spinX,ball.spinY].every(Number.isFinite))return false;if(Math.abs(ball.x)>5000||Math.abs(ball.y)>5000||Math.abs(ball.vx)>10000||Math.abs(ball.vy)>10000)return false}return expected.every(id=>seen.has(id))}
function recoverStaleBilliardsRooms(){const recovered=[];for(const room of db.rooms){if(room.status!=="STARTED"||!["EIGHT","SNOOKER"].includes(room.mode)||!room.game.rolling||!room.game.shotStartedAt||Date.now()-room.game.shotStartedAt<STALE_SHOT_MS)continue;room.game.currentTurn=1-room.game.currentTurn;room.game.rolling=false;room.game.activeShooter=null;room.game.shotToken=null;room.game.shotStartedAt=null;room.game.lastAction=null;room.revision++;if(room.game.snapshot){room.game.snapshot.currentTurn=room.game.currentTurn;room.game.snapshot.gameState="AIMING"}recovered.push(room)}if(!recovered.length)return;save();for(const room of recovered)roomEvent(room,{type:"ROOM_RECOVERED",roomId:room.id,revision:room.revision,room:publicRoom(room)})}
function bootstrap(user){const incoming=db.friendRequests.filter(r=>r.to===user.id&&r.status==="PENDING").map(r=>({...r,fromUser:publicUser(db.users.find(u=>u.id===r.from))}));const outgoing=db.friendRequests.filter(r=>r.from===user.id&&r.status==="PENDING").map(r=>({...r,toUser:publicUser(db.users.find(u=>u.id===r.to))}));const rooms=db.rooms.filter(r=>r.status!=="FINISHED"&&(r.hostId===user.id||r.guestId===user.id)).map(publicRoom);const roomInvites=db.rooms.filter(r=>r.status==="WAITING"&&r.invites.includes(user.id)).map(publicRoom);return{me:publicUser(user),friends:user.friends.map(fid=>db.users.find(u=>u.id===fid)).filter(Boolean).map(publicUser),incoming,outgoing,rooms,roomInvites,statusBits:STATUS}}
function handleChessAction(room,user,playerIndex,data,res){const state=room.game.chess||(room.game.chess=newGame("CHESS").chess);if(state.status!=="PLAYING")return fail(res,409,"棋局已经结束");if(state.currentTurn!==playerIndex)return fail(res,403,"还没轮到你");if(data.type==="CHESS_RESIGN"){state.winner=1-playerIndex;state.status="FINISHED";state.lastMove={resign:true,player:playerIndex};room.revision++;save();roomEvent(room,{type:"CHESS_STATE",roomId:room.id,revision:room.revision,state});return json(res,200,{ok:true,state})}if(data.type!=="CHESS_MOVE")return fail(res,400,"未知象棋操作");const from={x:Number(data.from?.x),y:Number(data.from?.y)},to={x:Number(data.to?.x),y:Number(data.to?.y)};if(!chessMoveLegal(state.board,playerIndex,from,to))return fail(res,400,"该走法不合法");const piece=state.board[from.y][from.x],captured=state.board[to.y][to.x]||null;state.board[to.y][to.x]=piece;state.board[from.y][from.x]=null;state.moveNumber++;state.lastMove={from,to,piece,captured,player:playerIndex};const opponent=1-playerIndex;if(captured&&chessType(captured)==="j"||!chessHasMove(state.board,opponent)){state.winner=playerIndex;state.status="FINISHED";state.currentTurn=playerIndex}else{state.currentTurn=opponent;state.check=chessInCheck(state.board,opponent)}room.game.currentTurn=state.currentTurn;room.revision++;save();roomEvent(room,{type:"CHESS_STATE",roomId:room.id,revision:room.revision,state});broadcastRefresh();return json(res,200,{ok:true,state})}
function finishBoardAction(room,eventType,state,res){room.game.currentTurn=state.currentTurn;room.revision++;save();roomEvent(room,{type:eventType,roomId:room.id,revision:room.revision,state});broadcastRefresh();return json(res,200,{ok:true,state})}
function fiveWon(board,x,y,color){for(const[dx,dy]of[[1,0],[0,1],[1,1],[1,-1]]){let count=1;for(const sign of[-1,1])for(let step=1;;step++){const nx=x+dx*step*sign,ny=y+dy*step*sign;if(board[ny]?.[nx]!==color)break;count++}if(count>=5)return true}return false}
function handleFiveAction(room,user,playerIndex,data,res){const state=room.game.five||(room.game.five=newGame("FIVE").five);if(state.status!=="PLAYING")return fail(res,409,"棋局已经结束");if(state.currentTurn!==playerIndex)return fail(res,403,"还没轮到你");if(data.type==="FIVE_RESIGN"){state.winner=1-playerIndex;state.status="FINISHED";state.lastMove={resign:true,player:playerIndex};return finishBoardAction(room,"FIVE_STATE",state,res)}if(data.type!=="FIVE_MOVE")return fail(res,400,"未知五子棋操作");const x=Number(data.x),y=Number(data.y);if(!Number.isInteger(x)||!Number.isInteger(y)||x<0||y<0||x>=state.size||y>=state.size)return fail(res,400,"落点超出棋盘");if(state.board[y][x])return fail(res,409,"该位置已有棋子");const color=playerIndex+1;state.board[y][x]=color;state.moveNumber++;state.lastMove={x,y,player:playerIndex};if(fiveWon(state.board,x,y,color)){state.winner=playerIndex;state.status="FINISHED"}else if(state.moveNumber===state.size*state.size){state.winner=-1;state.status="FINISHED"}else state.currentTurn=1-playerIndex;return finishBoardAction(room,"FIVE_STATE",state,res)}
function handleGoAction(room,user,playerIndex,data,res){const state=room.game.go||(room.game.go=newGame("GO").go);if(state.status!=="PLAYING")return fail(res,409,"棋局已经结束");if(state.currentTurn!==playerIndex)return fail(res,403,"还没轮到你");if(data.type==="GO_RESIGN"){state.winner=1-playerIndex;state.status="FINISHED";state.result={reason:"RESIGN",winner:state.winner};state.lastMove={resign:true,player:playerIndex};return finishBoardAction(room,"GO_STATE",state,res)}if(data.type==="GO_PASS"){state.moveNumber++;state.passCount++;state.lastMove={pass:true,player:playerIndex};if(state.passCount>=2){const score=goScore(state.board,state.komi);state.result={reason:"SCORE",score};state.winner=score.black>score.white?0:1;state.status="FINISHED"}else state.currentTurn=1-playerIndex;return finishBoardAction(room,"GO_STATE",state,res)}if(data.type!=="GO_MOVE")return fail(res,400,"未知围棋操作");const x=Number(data.x),y=Number(data.y);if(!Number.isInteger(x)||!Number.isInteger(y)||x<0||y<0||x>=state.size||y>=state.size)return fail(res,400,"落点超出棋盘");if(state.board[y][x])return fail(res,409,"该位置已有棋子");const board=cloneBoard(state.board),color=playerIndex+1,enemy=color===1?2:1;board[y][x]=color;let captured=0;for(const[nx,ny]of gridNeighbors(x,y,state.size)){if(board[ny][nx]!==enemy)continue;const group=goGroup(board,nx,ny);if(group.liberties.size===0)for(const[gx,gy]of group.stones){board[gy][gx]=0;captured++}}if(goGroup(board,x,y).liberties.size===0)return fail(res,409,"禁入点：不能自杀");const hash=boardHash(board);if(state.history.includes(hash))return fail(res,409,"劫争：不能立即还原到旧局面");state.board=board;state.captures[playerIndex]+=captured;state.moveNumber++;state.passCount=0;state.lastMove={x,y,player:playerIndex,captured};state.history.push(hash);state.currentTurn=1-playerIndex;return finishBoardAction(room,"GO_STATE",state,res)}
function beginNextRound(room,recordFinished){if(recordFinished)recordRoomResult(room);const round=(room.game.round||1)+1;room.game=newGame(room.mode);room.game.round=round;room.revision++;save();const publicState=publicRoom(room);roomEvent(room,{type:"ROOM_REMATCH",roomId:room.id,revision:room.revision,room:publicState});broadcastRefresh();return publicState}

async function api(req,res,url){
  if(req.method==="POST"&&url.pathname==="/api/auth/register"){const data=await body(req),username=String(data.username||"").trim(),password=String(data.password||"");if(!/^[\p{L}\p{N}_-]{3,16}$/u.test(username))return fail(res,400,"用户名需为3-16位文字、数字、下划线或短横线");if(password.length<6||password.length>72)return fail(res,400,"密码需为6-72位");if(db.users.some(u=>u.username.toLowerCase()===username.toLowerCase()))return fail(res,409,"用户名已存在");const encoded=hashPassword(password),user={id:id("usr"),username,salt:encoded.salt,passwordHash:encoded.hash,friends:[],createdAt:now()};db.users.push(user);save();json(res,201,{user:publicUser(user)},setSession(res,user.id));broadcastRefresh();return}
  if(req.method==="POST"&&url.pathname==="/api/auth/login"){const data=await body(req),user=db.users.find(u=>u.username.toLowerCase()===String(data.username||"").trim().toLowerCase());if(!user||!verifyPassword(String(data.password||""),user))return fail(res,401,"用户名或密码错误");json(res,200,{user:publicUser(user)},setSession(res,user.id));broadcastRefresh();return}
  if(req.method==="POST"&&url.pathname==="/api/auth/logout"){const sid=cookies(req).sid,userId=sessions.get(sid);sessions.delete(sid);json(res,200,{ok:true},{"Set-Cookie":"sid=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0"});if(userId)broadcastRefresh();return}
  const user=requireAuth(req,res);if(!user)return;
  if(req.method==="GET"&&url.pathname==="/api/leaderboard"){const mode=String(url.searchParams.get("mode")||"EIGHT");if(!modeName(mode))return fail(res,400,"不支持的游戏模式");const ranking=db.users.map(player=>{const stat=ensureStats(player)[mode],games=stat.wins+stat.losses+stat.draws;return{id:player.id,username:player.username,wins:stat.wins,losses:stat.losses,draws:stat.draws,games,winRate:stat.wins+stat.losses?Math.round(stat.wins/(stat.wins+stat.losses)*100):0}}).sort((a,b)=>b.wins-a.wins||a.losses-b.losses||b.winRate-a.winRate||a.username.localeCompare(b.username,"zh-CN")).map((entry,index)=>({...entry,rank:index+1}));return json(res,200,{mode,ranking})}
  const gameplayMatch=url.pathname.match(/^\/api\/rooms\/([^/]+)\/(action|board-action)$/);if(req.method==="POST"&&gameplayMatch){const gameplayRoom=requireRoom(req,res,gameplayMatch[1],user);if(!gameplayRoom)return;if(gameplayRoom.game.restartRequest)return fail(res,409,"正在等待对手确认是否重新开始")}
  let systemMatch=url.pathname.match(/^\/api\/rooms\/([^/]+)\/(resign|rematch)$/);if(req.method==="POST"&&systemMatch){const room=requireRoom(req,res,systemMatch[1],user);if(!room)return;if(room.status!=="STARTED"||!room.guestId)return fail(res,409,"对局尚未开始");const playerIndex=room.hostId===user.id?0:1,operation=systemMatch[2],result=settledResult(room);if(operation==="resign"){if(result.done)return fail(res,409,"本局已经结束");room.game.finished=true;room.game.winner=1-playerIndex;room.game.rolling=false;room.game.activeShooter=null;room.game.restartRequest=null;room.game.lastAction={type:"RESIGN",player:playerIndex};room.revision++;save();roomEvent(room,{type:"ROOM_FINISHED",roomId:room.id,revision:room.revision,winner:room.game.winner,resigned:playerIndex,game:publicRoom(room).game});broadcastRefresh();return json(res,200,{ok:true,room:publicRoom(room)})}const data=await body(req),expectedRound=Number(data.round);if(Number.isInteger(expectedRound)&&expectedRound!==room.game.round)return fail(res,409,"对局已经更新，请勿重复操作");if(result.done){const nextRoom=beginNextRound(room,true);return json(res,200,{ok:true,started:true,room:nextRoom})}const pending=room.game.restartRequest;if(data.response==="ACCEPT"||data.response==="DECLINE"){if(!pending||pending.to!==playerIndex||pending.id!==data.requestId)return fail(res,409,"重开请求已失效");if(data.response==="DECLINE"){room.game.restartRequest=null;room.revision++;save();roomEvent(room,{type:"RESTART_DECLINED",roomId:room.id,revision:room.revision,by:playerIndex});return json(res,200,{ok:true,started:false,declined:true})}const nextRoom=beginNextRound(room,false);return json(res,200,{ok:true,started:true,room:nextRoom})}if(pending){if(pending.from===playerIndex)return json(res,200,{ok:true,started:false,pending});return fail(res,409,"对手已经请求重新开始，请先确认或取消")}const opponent=1-playerIndex,request={id:id("restart"),from:playerIndex,to:opponent,round:room.game.round,createdAt:now()};room.game.restartRequest=request;room.revision++;save();sendEvent(opponent===0?room.hostId:room.guestId,{type:"RESTART_REQUEST",roomId:room.id,revision:room.revision,request});return json(res,200,{ok:true,started:false,pending:request})}
  let boardMatch=url.pathname.match(/^\/api\/rooms\/([^/]+)\/board-action$/);if(req.method==="POST"&&boardMatch){const room=requireRoom(req,res,boardMatch[1],user);if(!room)return;if(room.status!=="STARTED")return fail(res,409,"游戏尚未开始");const data=await body(req),playerIndex=room.hostId===user.id?0:1;if(room.mode==="FIVE")return handleFiveAction(room,user,playerIndex,data,res);if(room.mode==="GO")return handleGoAction(room,user,playerIndex,data,res);return fail(res,400,"该房间不是棋盘游戏")}
  if(req.method==="GET"&&url.pathname==="/api/bootstrap")return json(res,200,bootstrap(user));
  if(req.method==="GET"&&url.pathname==="/api/users"){const q=(url.searchParams.get("q")||"").trim().toLowerCase();const users=q?db.users.filter(u=>u.id!==user.id&&u.username.toLowerCase().includes(q)).slice(0,20):[];return json(res,200,{users:users.map(publicUser)});}
  if(req.method==="POST"&&url.pathname==="/api/friends/request"){const data=await body(req),target=db.users.find(u=>u.id===data.userId);if(!target||target.id===user.id)return fail(res,404,"用户不存在");if(user.friends.includes(target.id))return fail(res,409,"已经是好友");if(db.friendRequests.some(r=>r.status==="PENDING"&&((r.from===user.id&&r.to===target.id)||(r.from===target.id&&r.to===user.id))))return fail(res,409,"好友申请已存在");db.friendRequests.push({id:id("fr"),from:user.id,to:target.id,status:"PENDING",createdAt:now()});save();sendEvent(target.id,{type:"FRIEND_REQUEST"});json(res,201,{ok:true});broadcastRefresh();return}
  let match=url.pathname.match(/^\/api\/friends\/([^/]+)\/respond$/);if(req.method==="POST"&&match){const request=db.friendRequests.find(r=>r.id===match[1]&&r.to===user.id&&r.status==="PENDING");if(!request)return fail(res,404,"好友申请不存在");const data=await body(req);request.status=data.accept?"ACCEPTED":"DECLINED";if(data.accept){const other=db.users.find(u=>u.id===request.from);if(!user.friends.includes(other.id))user.friends.push(other.id);if(!other.friends.includes(user.id))other.friends.push(user.id)}save();json(res,200,{ok:true});broadcastRefresh();return}
  if(req.method==="POST"&&url.pathname==="/api/rooms"){const data=await body(req),mode=String(data.mode||"");if(!modeName(mode))return fail(res,400,"不支持的游戏模式");if(activeRoom(user.id))return fail(res,409,"你已经在房间或游戏中");const room={id:id("room"),hostId:user.id,guestId:null,mode,status:"WAITING",modeLocked:false,invites:[],revision:0,createdAt:now(),game:newGame(mode)};db.rooms.push(room);save();json(res,201,{room:publicRoom(room)});broadcastRefresh();return}
  match=url.pathname.match(/^\/api\/rooms\/([^/]+)$/);if(req.method==="GET"&&match){const room=requireRoom(req,res,match[1],user);if(room)return json(res,200,{room:publicRoom(room),me:publicUser(user)});return}
  match=url.pathname.match(/^\/api\/rooms\/([^/]+)\/mode$/);if(req.method==="PATCH"&&match){const room=requireRoom(req,res,match[1],user);if(!room)return;if(room.hostId!==user.id)return fail(res,403,"只有房主可以修改模式");if(room.modeLocked||room.status!=="WAITING")return fail(res,409,"游戏开始后不能更改模式");const data=await body(req);if(!modeName(data.mode))return fail(res,400,"不支持的游戏模式");room.mode=data.mode;save();json(res,200,{room:publicRoom(room)});roomEvent(room,{type:"ROOM_UPDATED"});broadcastRefresh();return}
  match=url.pathname.match(/^\/api\/rooms\/([^/]+)\/invite$/);if(req.method==="POST"&&match){const room=requireRoom(req,res,match[1],user);if(!room)return;if(room.hostId!==user.id)return fail(res,403,"只有房主可以邀请");if(room.status!=="WAITING"||room.guestId)return fail(res,409,"房间已满或已经开始");const data=await body(req),target=db.users.find(u=>u.id===data.userId);if(!target||!user.friends.includes(target.id))return fail(res,400,"只能邀请好友");const status=statusOf(target.id);if(!(status&STATUS.ONLINE))return fail(res,409,"好友当前不在线");if(status&(STATUS.IN_ROOM|STATUS.IN_GAME))return fail(res,409,"好友正在房间或游戏中");if(!room.invites.includes(target.id))room.invites.push(target.id);save();sendEvent(target.id,{type:"ROOM_INVITE",room:publicRoom(room)});json(res,200,{ok:true});broadcastRefresh();return}
  match=url.pathname.match(/^\/api\/rooms\/([^/]+)\/invite-response$/);if(req.method==="POST"&&match){const room=db.rooms.find(r=>r.id===match[1]&&r.invites.includes(user.id));if(!room||room.status!=="WAITING")return fail(res,404,"邀请已失效");const data=await body(req);room.invites=room.invites.filter(uid=>uid!==user.id);if(data.accept){if(activeRoom(user.id))return fail(res,409,"你已经在其他房间或游戏中");if(room.guestId)return fail(res,409,"房间已满");room.guestId=user.id;room.invites=[]}save();json(res,200,{room:data.accept?publicRoom(room):null});roomEvent(room,{type:"ROOM_UPDATED"});broadcastRefresh();return}
  match=url.pathname.match(/^\/api\/rooms\/([^/]+)\/start$/);if(req.method==="POST"&&match){const room=requireRoom(req,res,match[1],user);if(!room)return;if(room.hostId!==user.id)return fail(res,403,"只有房主可以开始");if(room.status!=="WAITING"||!room.guestId)return fail(res,409,"需要两名玩家才能开始");room.status="STARTED";room.modeLocked=true;room.game=newGame(room.mode);room.revision++;save();json(res,200,{room:publicRoom(room)});roomEvent(room,{type:"ROOM_STARTED",room:publicRoom(room)});broadcastRefresh();return}
  match=url.pathname.match(/^\/api\/rooms\/([^/]+)\/exit$/);if(req.method==="POST"&&match){const room=requireRoom(req,res,match[1],user);if(!room)return;if(room.status==="STARTED"){room.status="FINISHED";room.game.rolling=false;roomEvent(room,{type:"ROOM_CLOSED",reason:`${user.username} 已退出游戏`})}else if(room.hostId===user.id){room.status="FINISHED";roomEvent(room,{type:"ROOM_CLOSED",reason:"房主已关闭房间"})}else{room.guestId=null;room.invites=[];roomEvent(room,{type:"ROOM_UPDATED"})}save();json(res,200,{ok:true});broadcastRefresh();return}
  match=url.pathname.match(/^\/api\/rooms\/([^/]+)\/action$/);
  if(req.method==="POST"&&match){
    const room=requireRoom(req,res,match[1],user);if(!room)return;if(room.status!=="STARTED")return fail(res,409,"游戏尚未开始");
    const data=await body(req),playerIndex=room.hostId===user.id?0:1;
    if(room.mode==="CHESS")return handleChessAction(room,user,playerIndex,data,res);
    if(data.type==="PREVIEW"){
      if(room.game.rolling)return fail(res,409,"上一杆尚未结束");if(room.game.currentTurn!==playerIndex)return fail(res,403,"还没轮到你");
      const preview={aim:data.aim,power:Number(data.power)||0,spin:data.spin,cue:data.cue,charging:!!data.charging};roomEvent(room,{type:"ROOM_PREVIEW",roomId:room.id,senderId:user.id,preview});return json(res,200,{ok:true});
    }
    if(data.type==="SHOT"){
      if(room.game.rolling)return fail(res,409,"上一杆尚未结束");if(room.game.currentTurn!==playerIndex)return fail(res,403,"还没轮到你");
      const action={type:"SHOT",aim:data.aim,power:data.power,spin:data.spin,cue:data.cue,freeBallId:data.freeBallId||null};
      room.game.rolling=true;room.game.activeShooter=user.id;room.game.shotToken=id("shot");room.game.shotStartedAt=Date.now();room.game.lastAction=action;room.revision++;save();
      const event={type:"ROOM_ACTION",roomId:room.id,revision:room.revision,senderId:user.id,shotToken:room.game.shotToken,action};roomEvent(room,event);return json(res,200,{ok:true,revision:room.revision,shotToken:room.game.shotToken});
    }
    if(data.type==="STATE"){
      if(!room.game.shotToken||data.shotToken!==room.game.shotToken)return fail(res,409,"该杆结算已过期");
      /* 正常由击球方提交；若击球方掉线，另一方在两秒后也可用同一令牌补交，避免房间永久锁死。 */
      const fallbackReady=Date.now()-Number(room.game.shotStartedAt||0)>=2000;if(room.game.activeShooter!==user.id&&!fallbackReady)return fail(res,409,"等待击球方结算");
      if(!validBilliardsSnapshot(data.snapshot,room.mode))return fail(res,400,"局面数据无效");
      const shotToken=room.game.shotToken;room.game.snapshot=data.snapshot;room.game.currentTurn=data.snapshot.currentTurn;room.game.rolling=false;room.game.activeShooter=null;room.game.shotToken=null;room.game.shotStartedAt=null;room.game.lastAction=null;room.revision++;save();
      roomEvent(room,{type:"ROOM_STATE",roomId:room.id,revision:room.revision,senderId:user.id,shotToken,snapshot:data.snapshot});return json(res,200,{ok:true,revision:room.revision});
    }
    return fail(res,400,"未知游戏动作");
  }
  fail(res,404,"接口不存在");
}

function openStream(req,res,user){res.writeHead(200,{"Content-Type":"text/event-stream; charset=utf-8","Cache-Control":"no-cache, no-transform","Connection":"keep-alive","X-Accel-Buffering":"no"});res.write(`data: ${JSON.stringify({type:"CONNECTED",me:publicUser(user)})}\n\n`);if(!streams.has(user.id))streams.set(user.id,new Set());streams.get(user.id).add(res);broadcastRefresh();const timer=setInterval(()=>res.write(": ping\n\n"),25000);req.on("close",()=>{clearInterval(timer);const set=streams.get(user.id);if(set){set.delete(res);if(!set.size)streams.delete(user.id)}broadcastRefresh()})}
const STATIC={"/":"lobby.html","/lobby.html":"lobby.html","/billiards.html":"billiards.html","/chess.html":"chess.html","/five.html":"five.html","/go.html":"go.html","/index.html":"index.html"};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,"http://localhost");if(url.pathname==="/api/events"){const user=requireAuth(req,res);if(user)openStream(req,res,user);return}if(url.pathname.startsWith("/api/")){await api(req,res,url);return}const file=STATIC[url.pathname];if(!file)return fail(res,404,"页面不存在");const content=fs.readFileSync(path.join(ROOT,file));res.writeHead(200,{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-cache"});res.end(content)}catch(error){console.error(error);fail(res,500,error.message||"服务器错误")}});
const staleRoomTimer=setInterval(recoverStaleBilliardsRooms,5000);staleRoomTimer.unref();
server.listen(PORT,()=>console.log(`Black Gold Game Server running at http://localhost:${PORT}`));
