"use strict";
const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const ROOT=__dirname,DB_FILE=process.env.DB_FILE?path.resolve(process.env.DB_FILE):path.join(ROOT,"data","db.json"),DATA_DIR=path.dirname(DB_FILE),PORT=Number(process.env.PORT)||80;
const STATUS=Object.freeze({OFFLINE:0,ONLINE:1,IN_ROOM:2,IN_GAME:4});
if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true});
if(!fs.existsSync(DB_FILE))fs.writeFileSync(DB_FILE,JSON.stringify({users:[],friendRequests:[],rooms:[]},null,2));
let db=JSON.parse(fs.readFileSync(DB_FILE,"utf8"));db.users||=[];db.friendRequests||=[];db.rooms||=[];
const sessions=new Map(),streams=new Map();
const id=prefix=>`${prefix}_${crypto.randomBytes(8).toString("hex")}`;
const now=()=>new Date().toISOString();
function save(){const tmp=DB_FILE+".tmp";fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,DB_FILE)}
function cookies(req){return Object.fromEntries((req.headers.cookie||"").split(";").map(v=>v.trim().split("=")).filter(v=>v.length===2).map(([k,v])=>[k,decodeURIComponent(v)]))}
function currentUser(req){const userId=sessions.get(cookies(req).sid);return db.users.find(user=>user.id===userId)||null}
function activeRoom(userId){return db.rooms.find(room=>room.status!=="FINISHED"&&(room.hostId===userId||room.guestId===userId))||null}
function statusOf(userId){let value=streams.get(userId)?.size?STATUS.ONLINE:STATUS.OFFLINE,room=activeRoom(userId);if(room)value|=room.status==="STARTED"?STATUS.IN_GAME:STATUS.IN_ROOM;return value}
function publicUser(user){return{id:user.id,username:user.username,status:statusOf(user.id),createdAt:user.createdAt}}
function publicRoom(room){return{id:room.id,host:publicUser(db.users.find(u=>u.id===room.hostId)),guest:room.guestId?publicUser(db.users.find(u=>u.id===room.guestId)):null,mode:room.mode,status:room.status,modeLocked:room.modeLocked,revision:room.revision,createdAt:room.createdAt,game:{currentTurn:room.game.currentTurn,rolling:room.game.rolling,snapshot:room.game.snapshot,lastAction:room.game.lastAction||null,activeShooter:room.game.activeShooter||null}}}
function json(res,status,data,headers={}){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...headers});res.end(JSON.stringify(data))}
function fail(res,status,message){json(res,status,{error:message})}
async function body(req){let raw="";for await(const chunk of req){raw+=chunk;if(raw.length>1e6)throw Error("请求过大")}if(!raw)return{};try{return JSON.parse(raw)}catch{throw Error("JSON 格式错误")}}
function hashPassword(password,salt=crypto.randomBytes(16).toString("hex")){return{salt,hash:crypto.scryptSync(password,salt,64).toString("hex")}}
function verifyPassword(password,user){const candidate=hashPassword(password,user.salt).hash;return crypto.timingSafeEqual(Buffer.from(candidate,"hex"),Buffer.from(user.passwordHash,"hex"))}
function sendEvent(userId,event){for(const res of streams.get(userId)||[]){res.write(`data: ${JSON.stringify(event)}\n\n`)}}
function broadcastRefresh(){for(const userId of streams.keys())sendEvent(userId,{type:"REFRESH",at:Date.now()})}
function roomEvent(room,event){for(const userId of [room.hostId,room.guestId].filter(Boolean))sendEvent(userId,event)}
function setSession(res,userId){const sid=crypto.randomBytes(24).toString("hex");sessions.set(sid,userId);return{"Set-Cookie":`sid=${sid}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800`}}
function requireAuth(req,res){const user=currentUser(req);if(!user)fail(res,401,"请先登录");return user}
function requireRoom(req,res,roomId,user){const room=db.rooms.find(r=>r.id===roomId);if(!room){fail(res,404,"房间不存在");return null}if(room.hostId!==user.id&&room.guestId!==user.id){fail(res,403,"你不在该房间");return null}return room}
function modeName(mode){return mode==="SNOOKER"?"斯诺克":mode==="EIGHT"?"中式八球":null}
function bootstrap(user){const incoming=db.friendRequests.filter(r=>r.to===user.id&&r.status==="PENDING").map(r=>({...r,fromUser:publicUser(db.users.find(u=>u.id===r.from))}));const outgoing=db.friendRequests.filter(r=>r.from===user.id&&r.status==="PENDING").map(r=>({...r,toUser:publicUser(db.users.find(u=>u.id===r.to))}));const rooms=db.rooms.filter(r=>r.status!=="FINISHED"&&(r.hostId===user.id||r.guestId===user.id)).map(publicRoom);const roomInvites=db.rooms.filter(r=>r.status==="WAITING"&&r.invites.includes(user.id)).map(publicRoom);return{me:publicUser(user),friends:user.friends.map(fid=>db.users.find(u=>u.id===fid)).filter(Boolean).map(publicUser),incoming,outgoing,rooms,roomInvites,statusBits:STATUS}}

async function api(req,res,url){
  if(req.method==="POST"&&url.pathname==="/api/auth/register"){const data=await body(req),username=String(data.username||"").trim(),password=String(data.password||"");if(!/^[\p{L}\p{N}_-]{3,16}$/u.test(username))return fail(res,400,"用户名需为3-16位文字、数字、下划线或短横线");if(password.length<6||password.length>72)return fail(res,400,"密码需为6-72位");if(db.users.some(u=>u.username.toLowerCase()===username.toLowerCase()))return fail(res,409,"用户名已存在");const encoded=hashPassword(password),user={id:id("usr"),username,salt:encoded.salt,passwordHash:encoded.hash,friends:[],createdAt:now()};db.users.push(user);save();json(res,201,{user:publicUser(user)},setSession(res,user.id));broadcastRefresh();return}
  if(req.method==="POST"&&url.pathname==="/api/auth/login"){const data=await body(req),user=db.users.find(u=>u.username.toLowerCase()===String(data.username||"").trim().toLowerCase());if(!user||!verifyPassword(String(data.password||""),user))return fail(res,401,"用户名或密码错误");json(res,200,{user:publicUser(user)},setSession(res,user.id));broadcastRefresh();return}
  if(req.method==="POST"&&url.pathname==="/api/auth/logout"){const sid=cookies(req).sid,userId=sessions.get(sid);sessions.delete(sid);json(res,200,{ok:true},{"Set-Cookie":"sid=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0"});if(userId)broadcastRefresh();return}
  const user=requireAuth(req,res);if(!user)return;
  if(req.method==="GET"&&url.pathname==="/api/bootstrap")return json(res,200,bootstrap(user));
  if(req.method==="GET"&&url.pathname==="/api/users"){const q=(url.searchParams.get("q")||"").trim().toLowerCase();const users=q?db.users.filter(u=>u.id!==user.id&&u.username.toLowerCase().includes(q)).slice(0,20):[];return json(res,200,{users:users.map(publicUser)});}
  if(req.method==="POST"&&url.pathname==="/api/friends/request"){const data=await body(req),target=db.users.find(u=>u.id===data.userId);if(!target||target.id===user.id)return fail(res,404,"用户不存在");if(user.friends.includes(target.id))return fail(res,409,"已经是好友");if(db.friendRequests.some(r=>r.status==="PENDING"&&((r.from===user.id&&r.to===target.id)||(r.from===target.id&&r.to===user.id))))return fail(res,409,"好友申请已存在");db.friendRequests.push({id:id("fr"),from:user.id,to:target.id,status:"PENDING",createdAt:now()});save();sendEvent(target.id,{type:"FRIEND_REQUEST"});json(res,201,{ok:true});broadcastRefresh();return}
  let match=url.pathname.match(/^\/api\/friends\/([^/]+)\/respond$/);if(req.method==="POST"&&match){const request=db.friendRequests.find(r=>r.id===match[1]&&r.to===user.id&&r.status==="PENDING");if(!request)return fail(res,404,"好友申请不存在");const data=await body(req);request.status=data.accept?"ACCEPTED":"DECLINED";if(data.accept){const other=db.users.find(u=>u.id===request.from);if(!user.friends.includes(other.id))user.friends.push(other.id);if(!other.friends.includes(user.id))other.friends.push(user.id)}save();json(res,200,{ok:true});broadcastRefresh();return}
  if(req.method==="POST"&&url.pathname==="/api/rooms"){const data=await body(req),mode=String(data.mode||"");if(!modeName(mode))return fail(res,400,"不支持的游戏模式");if(activeRoom(user.id))return fail(res,409,"你已经在房间或游戏中");const room={id:id("room"),hostId:user.id,guestId:null,mode,status:"WAITING",modeLocked:false,invites:[],revision:0,createdAt:now(),game:{currentTurn:0,rolling:false,activeShooter:null,snapshot:null,lastAction:null}};db.rooms.push(room);save();json(res,201,{room:publicRoom(room)});broadcastRefresh();return}
  match=url.pathname.match(/^\/api\/rooms\/([^/]+)$/);if(req.method==="GET"&&match){const room=requireRoom(req,res,match[1],user);if(room)return json(res,200,{room:publicRoom(room),me:publicUser(user)});return}
  match=url.pathname.match(/^\/api\/rooms\/([^/]+)\/mode$/);if(req.method==="PATCH"&&match){const room=requireRoom(req,res,match[1],user);if(!room)return;if(room.hostId!==user.id)return fail(res,403,"只有房主可以修改模式");if(room.modeLocked||room.status!=="WAITING")return fail(res,409,"游戏开始后不能更改模式");const data=await body(req);if(!modeName(data.mode))return fail(res,400,"不支持的游戏模式");room.mode=data.mode;save();json(res,200,{room:publicRoom(room)});roomEvent(room,{type:"ROOM_UPDATED"});broadcastRefresh();return}
  match=url.pathname.match(/^\/api\/rooms\/([^/]+)\/invite$/);if(req.method==="POST"&&match){const room=requireRoom(req,res,match[1],user);if(!room)return;if(room.hostId!==user.id)return fail(res,403,"只有房主可以邀请");if(room.status!=="WAITING"||room.guestId)return fail(res,409,"房间已满或已经开始");const data=await body(req),target=db.users.find(u=>u.id===data.userId);if(!target||!user.friends.includes(target.id))return fail(res,400,"只能邀请好友");const status=statusOf(target.id);if(!(status&STATUS.ONLINE))return fail(res,409,"好友当前不在线");if(status&(STATUS.IN_ROOM|STATUS.IN_GAME))return fail(res,409,"好友正在房间或游戏中");if(!room.invites.includes(target.id))room.invites.push(target.id);save();sendEvent(target.id,{type:"ROOM_INVITE",room:publicRoom(room)});json(res,200,{ok:true});broadcastRefresh();return}
  match=url.pathname.match(/^\/api\/rooms\/([^/]+)\/invite-response$/);if(req.method==="POST"&&match){const room=db.rooms.find(r=>r.id===match[1]&&r.invites.includes(user.id));if(!room||room.status!=="WAITING")return fail(res,404,"邀请已失效");const data=await body(req);room.invites=room.invites.filter(uid=>uid!==user.id);if(data.accept){if(activeRoom(user.id))return fail(res,409,"你已经在其他房间或游戏中");if(room.guestId)return fail(res,409,"房间已满");room.guestId=user.id;room.invites=[]}save();json(res,200,{room:data.accept?publicRoom(room):null});roomEvent(room,{type:"ROOM_UPDATED"});broadcastRefresh();return}
  match=url.pathname.match(/^\/api\/rooms\/([^/]+)\/start$/);if(req.method==="POST"&&match){const room=requireRoom(req,res,match[1],user);if(!room)return;if(room.hostId!==user.id)return fail(res,403,"只有房主可以开始");if(room.status!=="WAITING"||!room.guestId)return fail(res,409,"需要两名玩家才能开始");room.status="STARTED";room.modeLocked=true;room.game={currentTurn:0,rolling:false,activeShooter:null,snapshot:null,lastAction:null};room.revision++;save();json(res,200,{room:publicRoom(room)});roomEvent(room,{type:"ROOM_STARTED",room:publicRoom(room)});broadcastRefresh();return}
  match=url.pathname.match(/^\/api\/rooms\/([^/]+)\/exit$/);if(req.method==="POST"&&match){const room=requireRoom(req,res,match[1],user);if(!room)return;if(room.status==="STARTED"){room.status="FINISHED";room.game.rolling=false;roomEvent(room,{type:"ROOM_CLOSED",reason:`${user.username} 已退出游戏`})}else if(room.hostId===user.id){room.status="FINISHED";roomEvent(room,{type:"ROOM_CLOSED",reason:"房主已关闭房间"})}else{room.guestId=null;room.invites=[];roomEvent(room,{type:"ROOM_UPDATED"})}save();json(res,200,{ok:true});broadcastRefresh();return}
  match=url.pathname.match(/^\/api\/rooms\/([^/]+)\/action$/);if(req.method==="POST"&&match){const room=requireRoom(req,res,match[1],user);if(!room)return;if(room.status!=="STARTED")return fail(res,409,"游戏尚未开始");const data=await body(req),playerIndex=room.hostId===user.id?0:1;if(data.type==="PREVIEW"){if(room.game.rolling)return fail(res,409,"上一杆尚未结束");if(room.game.currentTurn!==playerIndex)return fail(res,403,"还没轮到你");const preview={aim:data.aim,power:Number(data.power)||0,spin:data.spin,cue:data.cue,charging:!!data.charging};roomEvent(room,{type:"ROOM_PREVIEW",roomId:room.id,senderId:user.id,preview});return json(res,200,{ok:true})}if(data.type==="SHOT"){if(room.game.rolling)return fail(res,409,"上一杆尚未结束");if(room.game.currentTurn!==playerIndex)return fail(res,403,"还没轮到你");const action={type:"SHOT",aim:data.aim,power:data.power,spin:data.spin,cue:data.cue,freeBallId:data.freeBallId||null};room.game.rolling=true;room.game.activeShooter=user.id;room.game.lastAction=action;room.revision++;save();const event={type:"ROOM_ACTION",roomId:room.id,revision:room.revision,senderId:user.id,action};roomEvent(room,event);return json(res,200,{ok:true,revision:room.revision})}if(data.type==="STATE"){if(room.game.activeShooter!==user.id)return fail(res,403,"只有本杆击球方可以提交结算");if(!data.snapshot||![0,1].includes(data.snapshot.currentTurn))return fail(res,400,"局面数据无效");room.game.snapshot=data.snapshot;room.game.currentTurn=data.snapshot.currentTurn;room.game.rolling=false;room.game.activeShooter=null;room.game.lastAction=null;room.revision++;save();roomEvent(room,{type:"ROOM_STATE",roomId:room.id,revision:room.revision,senderId:user.id,snapshot:data.snapshot});return json(res,200,{ok:true,revision:room.revision})}return fail(res,400,"未知游戏动作")}
  fail(res,404,"接口不存在");
}

function openStream(req,res,user){res.writeHead(200,{"Content-Type":"text/event-stream; charset=utf-8","Cache-Control":"no-cache, no-transform","Connection":"keep-alive","X-Accel-Buffering":"no"});res.write(`data: ${JSON.stringify({type:"CONNECTED",me:publicUser(user)})}\n\n`);if(!streams.has(user.id))streams.set(user.id,new Set());streams.get(user.id).add(res);broadcastRefresh();const timer=setInterval(()=>res.write(": ping\n\n"),25000);req.on("close",()=>{clearInterval(timer);const set=streams.get(user.id);if(set){set.delete(res);if(!set.size)streams.delete(user.id)}broadcastRefresh()})}
const STATIC={"/":"lobby.html","/lobby.html":"lobby.html","/billiards.html":"billiards.html","/index.html":"index.html","/go.html":"go.html"};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,"http://localhost");if(url.pathname==="/api/events"){const user=requireAuth(req,res);if(user)openStream(req,res,user);return}if(url.pathname.startsWith("/api/")){await api(req,res,url);return}const file=STATIC[url.pathname];if(!file)return fail(res,404,"页面不存在");const content=fs.readFileSync(path.join(ROOT,file));res.writeHead(200,{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-cache"});res.end(content)}catch(error){console.error(error);fail(res,500,error.message||"服务器错误")}});
server.listen(PORT,()=>console.log(`Billiards Club running at http://localhost:${PORT}`));
